### ISSUE TITLE
update mongodb to 3.4 in travis.yml

### ISSUE THREAD

**Issue by lebalz** [tageler/tageler-api#30]
MongoError: exception: Unrecognized pipeline stage name: '$addFields'
$addFields is introduced in mongoDb-version 3.4, but i could not figure out how to update.

**Comment by hairmare** [comment]
I know that you can get to 3.2 with the following in `.travis.yml`:

```yml
services:
- mongodb
- rabbitmq
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
```

I'm not sure about 3.4 it looks like there is only 3.2 in the [repo whitelist](https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L242-L256) for travis. It doesn't look like $addFields is already in 3.2, maybe skip those tests on travis when an old mongodb is detected? It could be possible to install the right version with `sudo: true` but those machines are slow.
